version: 2
updates:
  # Enable version updates for .NET/NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "zenix-maintainers"
    assignees:
      - "zenix-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "zenix-maintainers"
    assignees:
      - "zenix-maintainers"
    commit-message:
      prefix: "ci"
